CPPFLAGS=-O2 -Wall

Logging:
Haircut:
B:
Haircut_test:
MushroomMonster:
YourRankIsPure:
PickingUpChicks:
FileFixIt:
NumberSets:
Mousetrap:
CropTriangles:
Omino:
pancake:
DNASequencing:
CircularSequence:
Patterns:
CoolWords:
circles:
blackmoves:
gravity:
AB:
FoxBlocks:
AhoyPirates:
SegmentTree:
tile-cut:
ritual-circle:

